const TIME_FRAME_FOR_SUBGRAPH_ONE_HOUR = 1;
const TIME_FRAME_FOR_SUBGRAPH_FOUR_HOURS = 4;
const TIME_FRAME_FOR_SUBGRAPH_SIX_HOURS = 6;


module.exports = {
  TIME_FRAME_FOR_SUBGRAPH_ONE_HOUR,
  TIME_FRAME_FOR_SUBGRAPH_FOUR_HOURS,
  TIME_FRAME_FOR_SUBGRAPH_SIX_HOURS,
};
